apiVersion: v1
kind: Service
metadata:
  name: k8s-hello-nginx
spec:
  type: LoadBalancer
  selector:
    app: k8s-hello-nginx
  ports:
  - port: 3030
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-hello-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: k8s-hello-nginx
  template:
    metadata:
      labels:
        app: k8s-hello-nginx
    spec:
      containers:
      - name: k8s-hello-nginx
        image: muhammadsaadgondal/k8s-hello-nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
